### PR TITLE
use try...except in TextInput.value to account for python 3 strings

### PR DESCRIPTION
**Pull request by BMJHayward**
Is this ok?

I came across an import error when making the "farenheit to celsius" converter tutorial. I thought catching the ImportError might be good.

### CODE REVIEW

**Comment by BMJHayward** [comment]
Scrap this, I'll come back to it shortly.

**Comment by freakboy3742** [comment]
There's actually a better way than this provided by the Toga core libraries - toga.compat defines a "text" data type, which is unicode on Py2, and str on Py3. If you cast to "text" instead of specifically to "unicode", you'll get the same effect.

**Comment by BMJHayward** [comment]
Aha! I suspected you had something like this somewhere. I'll fix this up over weekend, and go through code+docs more before making any more PRs. Thanks for informing me of this.

**Comment by BMJHayward** [comment]
I've gone through everything and can't find anything like a "toga.compat.text" data type. Perhaps I've missed something? Is toga.compat meant to be like wand.compat.text? 

I also know of pyramid.compat and python-utils/compat.py. Grepping through toga hasn't found me anything like this so far.

I guess you could add the wand library, or implement a compat sub-module if there isn't one already. Sorry if I've missed something obvious here.

**Comment by freakboy3742** [comment]
Oops... you've caught me :-) I've got some local commits that I hadn't pushed. I've just pushed an update to toga-core: https://github.com/pybee/toga/blob/master/toga/compat.py

**Comment by BMJHayward** [comment]
Oh cool, thanks for letting me know

**Comment by BMJHayward** [comment]
So, I tried to squash my commits and now it's an embarrassing mess.
I'll make a new one with toga.compat.

**Pull request closed without merging**
